os: osx
osx_image: xcode11
language: swift
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - PROJECT=FetchRequests.xcodeproj
    - RUN_TESTS="YES"
  matrix:
    - SCHEME="FetchRequests-iOS" DESTINATION="name=iPhone 11 Pro"
    - SCHEME="FetchRequests-tvOS" DESTINATION="name=Apple TV 4K"
    - SCHEME="FetchRequests-watchOS" DESTINATION="name=Apple Watch Series 5 - 44mm" RUN_TESTS="NO"
    - SCHEME="FetchRequests-macOS" DESTINATION="arch=x86_64"
script:
  - set -o pipefail
  #- xcodebuild -version
  #- xcodebuild -showsdks
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty -c;
    else
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi
jobs:
  include:
    - stage: Pod Lint
      script:
        - pod lib lint --verbose --allow-warnings
    - stage: Example Project
      env:
        - SCHEME="iOS Example"
        - DESTINATION="OS=12.2,name=iPhone XS"
        - PROJECT="Example/iOS-Example.xcodeproj"
      script:
        - set -o pipefail
        - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c
after_success:
  - if [ $RUN_TESTS == "YES" ]; then
      bash <(curl -s https://codecov.io/bash);
    fi
